language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - travis_retry composer install --no-interaction --prefer-source --no-suggest

script: phpunit

cache:
  directories:
  - $HOME/.cache/composer
